### PR TITLE
upgrade genoboo version to 0.4.4

### PR DESCRIPTION
**Pull request by loraine-gueguen**
To use the last release of genoboo in galaxy.

Is there any change (new inputs) to add in the form @mboudet ?

### CODE REVIEW

**Comment by loraine-gueguen** [comment]
same error as https://github.com/galaxy-genome-annotation/galaxy-tools/pull/82#issuecomment-1576859467

**Comment by mboudet** [comment]
Should not have any changes in the form.

Regarding the issue, I did not manage to reproduce it with my own env, so not sure how to fix it.
(But the tool worked regardless, so not sure how to proceed)

**Comment by loraine-gueguen** [comment]
>Regarding the issue, I did not manage to reproduce it with my own env, so not sure how to fix it.
>(But the tool worked regardless, so not sure how to proceed)

What do you think @abretaud ?

**Comment by abretaud** [comment]
Thanks Loraine! Applied the change to #82, closing this one

No idea for fixing the error here, I have to look into it

**Pull request closed without merging**
