### PR TITLE
[WIP] Add support for pgtools/pgutil for chado tools

### PR DESCRIPTION
**Pull request by abretaud**
Doing the same as https://github.com/bgruening/galaxytools/pull/642 with Chado database
It works! Just need to update the remaining tools

### CODE REVIEW

**Comment by abretaud** [comment]
(and also make a new python-chado release with https://github.com/galaxy-genome-annotation/python-chado/pull/11, until then tests will probably fail)

**Comment by bgruening** [comment]
Oh wow, this is amazing! Glad this is working!!!

**Comment by bgruening** [comment]
Oh it is merged, wow, can't wait to see it in action!

**Comment by abretaud** [comment]
Yep, I'm not sure yet how to use it though, ideally there should be a way at the end to deploy a chado dataset to a stable url (with tripal, ...). Or maybe a tripal GIE? (my god, what kind of creature are we building!?)
Anyway, it's fun that it works!

**Pull request merged**
