### PR TITLE
AskOmics: Remove url and api key

### PR DESCRIPTION
**Pull request by xgaia**
ping @abretaud

### CODE REVIEW

**Comment by abretaud** [comment]
Hum, some errors while uploading to TS:
https://travis-ci.org/galaxy-genome-annotation/galaxy-tools/jobs/339048942#L558

The TS tries to execute the python code!?

**Comment by erasche** [comment]
ping @martenson, any ideas?

**Comment by martenson** [comment]
the webapollo.py codefile is being compiled, all these failing tools specify it

https://github.com/galaxyproject/galaxy/blob/dev/lib/galaxy/tools/__init__.py#L769

**Comment by abretaud** [comment]
Strange, now I don't understand how these tools got successfully uploaded the last time
Anyway, these python scripts need a few modules that are not default Galaxy dependencies: https://github.com/galaxy-genome-annotation/galaxy-tools/blob/298b77b9201b8efbffc9174d98027b9dd5ba558e/.travis.yml#L80

Do you see a way to upload them to the TS anyway?

**Comment by martenson** [comment]
@abretaud I looked into it yesterday and was confused about it. All commits are fairly new (i.e. after hg push works no more) and claim to be uploaded by planemo. The changeset `Changeset 0:cd595b5d890a (2017-09-11)` in `apollo_create_or_update` repo seems to have some inconsistency in calling the `create_or_update_organism.xml` file a python file, but that is probably just TS display bug. Similarly in `apollo_delete_features` and probably others.


So I do not know how the files got in without failing this compilation.

**Comment by abretaud** [comment]
@martenson Yeah it's confusing... Anyway, it looks like we won't be able to upload future updates of these tools? Wouldn't it be possible to force the upload somehow (like `planemo shed_update --even_if_code_does_not_compile` or `<code file="webapollo.py" force="true"/>`)? Or maybe use the tool requirements, but I guess the conda envs are not available to the toolshed when uploading a tools?

**Comment by martenson** [comment]
@abretaud I suspect this has changed on our side - so you can treat this as a bug, we will make this work.

**Comment by martenson** [comment]
fixed in https://github.com/galaxyproject/galaxy/pull/5510

**Pull request merged**
