### PR TITLE
Add python-chado tools

### PR DESCRIPTION
**Pull request by abretaud**
Some wrappers for python-chado, adapted from https://github.com/galaxy-genome-annotation/python-chado/tree/master/galaxy to make them a little prettier when possible
It's still WIP as some of them are broken, and I'd like to had more fancy stuff (like [pg_tools](https://github.com/bgruening/galaxytools/pull/642) some day??)

### CODE REVIEW

**Comment by abretaud** [comment]
Ok, these tools should be ok now, it would be cool to have a quick review before merging it if you have time!
I'm not very proud of https://github.com/galaxy-genome-annotation/galaxy-tools/pull/17/files#diff-58b58b36cf628902782add4a9a13ae66R62, but I see no other way to make sure that a gff file is loaded before loading featureprops in a workflow for example...
I found a few bugs in python-chado, so I'll release the 2.1.2 version today.

**Comment by erasche** [comment]
I've done exactly that hack before. I really wish galaxy would include some 'virtual' way of doing this without defining these files. I don't think there is a better option and that works well enough. Better than scheduling the job and just doing a `while check-if-ok do; sleep 1; done;` in the tool.

**Comment by abretaud** [comment]
It seems like I need a new review before merging this, @erasche would you have time for it? (it shouldn't break anything though, just new tools)

**Comment by abretaud** [comment]
thanks!

**Pull request merged**
