### PR TITLE
Adding askomics tool

### PR DESCRIPTION
**Pull request by xgaia**
@abretaud 

This tools allow the integration of galaxy datasets into a distant [AskOmics](https://github.com/askomics/askomics) .

Supported inputs: tabular, gff3, bed and ttl.

All options available by the askomics interface can be set with this tool.

### CODE REVIEW

**Comment by abretaud** [comment]
@erasche @bgruening What do you think about adding this askomics tool to this repo?
I told @xgaia to propose a PR here as it looks a lot like our tripal or apollo tools: it interacts with a distant server (with credentials) and there's no easy way to really test it.
Tell us if you're ok with it or if you'd prefer to move it to a specific repo

**Comment by erasche** [comment]
is this an ok answer? ;)

**Comment by abretaud** [comment]
It looks like an ok indeed! Thanks!

**Comment by bgruening** [comment]
:+1: thanks @xgaia!

**Pull request merged**
